### ISSUE TITLE
Implement read workflow BDD tests.

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/usdOpenAssetIOResolver#7] opened 2023-01-19 13:44 UTC
Implement a set of BDD test cases according to the following specifications:

```gherkin
Feature:

  Background:
    Given The OpenAssetIO USD Resolver is activated
    And the OpenAssetIO manager can resolve all asset references in a composite stage
    
  Scenario: Non-assetized USD documents can be loaded with the OpenAssetIO resolver activated.
    When a composite stage with raw file paths is loaded
    Then the stage is completely loaded
    
  Scenario: Assetized USD documents can be loaded with the OpenAssetIO resolver activated
    When a composite stage with asset references is loaded
    Then the stage is completely loaded
    
  Scenario: Assetized USD paths can be resolved search-path relative paths
    Given USD is configured with a search path containing the child component of a USD stage
    And the root component of the USD stage is at a different path
    When the composite stage is loaded
    Then the stage is completely loaded
    
  Scenario: Assetized USD paths will prefer current working directory to alternate search paths
    Given USD is configured with a search path containing the child component of a USD stage
    And the root component of the USD stage is at a different path.
    And a child component with the same name exists alongside the parent USD file
    When the composite stage is loaded
    Then the stage is completely loaded, with the data from the child component alongside the parent USD file

  Scenario: Loading a non-assetized child document from an assetized parent document
    Given the USD stage references a second level document by asset identifier
    And the second-level document references a third-level document by relative file path
    When the composite stage is loaded
    Then the stage is completely loaded

  Scenario: Loading an assetized child document from an non-assetized parent document
    Given the USD stage references a second level document by relative file path
    And the second-level document references a third-level document by asset identifier
    When the composite stage is loaded
    Then the stage is completely loaded
    
  Scenario: Unmanaged locatable content for resolve falls back to file path loading
    Given managementPolicy says that locatableContent is unmanaged for read
    And the manager recognises any string that beings with "/BAL" as an asset identifer
    And an asset identifier of "/BAL/file.usd" that resolves to the file "/resources/file2.usd"
    And a file called "/BAL/file.usd" on disk
    When "/BAL/file.usd" is resolved
    Then "/BAL/file.usd" is the result

  Scenario: Managed locatable content for resolve takes precedence over file path loading
    Given managementPolicy says that locatableContent is managed for read
    And the manager recognises any string that beings with "/BAL" as an asset identifer
    And an asset identifier of "/BAL/file.usd" that resolves to the file "/resources/file2.usd"
    And a file called "/BAL/file.usd" on disk
    When "/BAL/file.usd" is resolved
    Then "/resources/file2.usd" is the result
```

**Comment by foundrytom** [comment] 2023-01-20 09:41
Great stuff. What do you think to phrasing things in terms of the default resolver, vs describing it's own affects? On the basis that we dint want to encoding its specific behaviour in our ACs - as I think were aligned on the real AC being that the result of resolve is simply passed along?

What is the motivation for:

>  Scenario: Assetized USD paths will prefer current working directory to alternate search paths

Is this `ArDefaultResolver` passthrough validation or something we've specifically added?

>   Scenario: Unmanaged locatable content for resolve falls back to file path loading

Would it perhaps be more valuable to phrase this in terms of:
```
Given ...
<no and>
When the stage is loaded
Then the manager is no longer involved in stage composition
And all input paths are handled by the default resolver.
```

As we definitely need to capture the requirements around not invoking the API in these scenarios. We may need a few other scenarios too to capture our other requirements there for performance reasons.

>  Scenario: Managed locatable content for resolve takes precedence over file path loading

Can we phrase this in terms of the response to `isEntityRefererence` instead. We should never define behavior in terms of specific string contents - as entity references are opaque to everyone except the Manager.

**Comment by feltech** [comment] 2023-01-20 16:09
> What do you think to phrasing things in terms of the default resolver, vs describing it's own affects? On the basis that we dint want to encoding its specific behaviour in our ACs - as I think were aligned on the real AC being that the result of resolve is simply passed along?

When we looked it's a bit more complex than simply pass-through.  E.g. the `CreateIdentifier(assetPath, anchorPath)` will need special handling for the case where `assetPath` is a search-path relative path and `anchorPath` is an entity reference.  We need to assert that we preserve the search-path relative feature of the default resolver.

> What is the motivation for:
> 
> > Scenario: Assetized USD paths will prefer current working directory to alternate search paths
> 
> Is this `ArDefaultResolver` passthrough validation or something we've specifically added?

This validates that we obey the search path behaviour of the default resolver, which prefers the current working directory (which we believe changes as USD traverses the file hierarchy).  Though I am struggling to remember why we thought we needed this test (@elliotcmorris ?).


> > Scenario: Managed locatable content for resolve takes precedence over file path loading
> 
> Can we phrase this in terms of the response to `isEntityRefererence` instead. We should never define behavior in terms of specific string contents - as entity references are opaque to everyone except the Manager.

I don't see a problem with defining a concrete _example_ in terms of specific string contents.  This is not meant to define the behaviour requirements in a general sense, but rather define an example that demonstrates the required behaviour.

Having said that, I think we need to rephrase to remove some ambiguity here (and in the other scenarios). 

This specific scenario isn't demonstrating behaviour around `isEntityReference`, it's demonstrating `managementPolicy`.  I.e. `isEntityReference` shouldn't even be called if `managementPolicy` signals that `locateableContent` is unmanaged.

This example attempts to set up a scenario whereby if `managementPolicy` was not obeyed, then the manager would return a different file path, which we can detect.

We may need more examples that demonstrate `isEntityReference` being called before `resolve`. The other examples that mix file paths and entity references help with this. But conceivably those examples could still pass if things were done wrong (e.g. try to `resolve` everything and fail gracefully by passing-through, which would work but be incorrect).

How about something like

```gherkin
  Scenario: The manager is not queried for paths that are not entity references
    Given the manager resolves trait "locateableContent.location" to "somestring" for entity reference "bal:///inaccessible"
    But the manager does not consider "bal:///inaccessible" to be a valid entity reference
    When "bal:///inaccessible" is resolved via ArResolver
    Then "bal:///inaccessible" is the result
```

**Comment by foundrytom** [comment] 2023-01-20 18:09
> When we looked it's a bit more complex than simply pass-through. E.g. the `CreateIdentifier(assetPath, anchorPath)` will need special handling for the case where `assetPath` is a search-path relative path and `anchorPath` is an entity reference. We need to assert that we preserve the search-path relative feature of the default resolver.

Sorry yeah, was thinking for the cases that the behaviour we are trying to define is that it is a passthrough (see below).

> > Is this `ArDefaultResolver` passthrough validation or something we've specifically added?
> 
> This validates that we obey the search path behaviour of the default resolver, which prefers the current working directory (which we believe changes as USD traverses the file hierarchy). Though I am struggling to remember why we thought we needed this test (@elliotcmorris ?).

My concern here is that we have several test cases that aren't testing that we're a pass through, they're testing that we mimic the behaviour of USD's default resolver at this specific instance in time. 

To phrase it in terms of an AC, the AC would be that "the path resolved via OpenAssetIO is passed on to USDs standard path-handling mechanism, and behaves as if that path was present in the source data". That is the design goal, and the behaviour we need to encapsulate.

Given we're considering BDD as a concrete definition of product requirements, my fear is that phrasing it in terms of current behaviour of the implementation of `ArDefaultResolver` doesn't differentiate between us mimicking its functionality (maybe by coping the code, which has been discussed) or passing through. Pass through is a critical product requirement. If USD changes the behaviour of `ArDefaultResolver`, our plugin should follow suit. 

If a USD change also breaks all our tests, the current phrasing creates ambiguity as to what the correct steps are to remediate the situation. It doesnt state that it should be a mirror of the USD resolver, so It would be a perfectly legitimate interpretation of the relevant scenarios to edit our implementation to maintain existing behaviour, which is the opposite of what wed want to do to resolve the issue (change the tests to match USDs new behaviour). I think we've always agreed that the tests should describe what is expected to drive implementation and future maintenance?

> > > Scenario: Managed locatable content for resolve takes precedence over file path loading
> > 
> > 
> > Can we phrase this in terms of the response to `isEntityRefererence` instead. We should never define behavior in terms of specific string contents - as entity references are opaque to everyone except the Manager.
> 
> I don't see a problem with defining a concrete _example_ in terms of specific string contents. This is not meant to define the behaviour requirements in a general sense, but rather define an example that demonstrates the required behaviour.

Maybe thats what we need to settle on - what we really want to get our of BDD, as (due to the API-API nature of this project), if we're not going to use BDD to capture the designed behaviour, then we need to make sure we flesh out some other definition of this, so we know what that behaviour should be to be able to implement it.

Having examples at this level could be ok but we also need a definition of the driving logic?

From my perspective, the benefit of attempting to BDD here was to make sure we have a way of capturing the behaviour of the design, abstract from implementation details of that design. If were just using it as an alternative way to encode specific examples of some other definition of the design, I think we need to be careful about the cognitive and development overhead it is adding over our normal, simpler when/then approach.

> Having said that, I think we need to rephrase to remove some ambiguity here (and in the other scenarios).
> 
> This specific scenario isn't demonstrating behaviour around `isEntityReference`, it's demonstrating `managementPolicy`. I.e. `isEntityReference` shouldn't even be called if `managementPolicy` signals that `locateableContent` is unmanaged.

> This example attempts to set up a scenario whereby if `managementPolicy` was not obeyed, then the manager would return a different file path, which we can detect.

Is this definitely the right way to capture and test this? The way you described in the preceding sentence is a much better definition of what we need to test. ("`isEntityReference` shouldn't even be called if `managementPolicy` signals that `locateableContent` is unmanaged.").  

Referring back to the 'examples' discussion above, It seems like we might be trying to use gherkin to describe a black box tests that infers that the implementation is doing what we want it to do, by wrapping up expected behaviours of a third-party system. Rather than to define the behaviour that drives that result.  We do have actual hard product-level requirements that certain API methods are used etc... to ensure we meet their contracts, so it feels to make sense to reflect this in how we describe the behaviour. 

> We may need more examples that demonstrate isEntityReference being called before resolve. 

Sorry, mentioning `isEntityReference` before was probably a bad example, as the API won't actually let you do that anyway now. I meant more that if its not a reference then we don't attempt to resolve it.

> How about something like
> ```
>   Scenario: The manager is not queried for paths that are not entity references
>     Given the manager resolves trait "locateableContent.location" to "somestring" for entity reference "bal:///inaccessible"
>     But the manager does not consider "bal:///inaccessible" to be a valid entity reference
>     When "bal:///inaccessible" is resolved via ArResolver
>     Then "bal:///inaccessible" is the result
> ```

Its quite hard to grok, as it feels a bit incongruous that the manager would have an answer for something that it thinks invalid. 

Would we want to use proper mechanisms to test scenarios like these too (eg: mocks/ the audit functionality in OpenAssetIO), rather than inferring the result? That scenario is perhaps more 'non references are passed through"?

I think we need to be careful about what were trying to use BDD for. I feels like were trying to cross the streams a little.  I think (and from the discussions today) defining all test cases for this work through gherkin is going to prove challenging (though solving this dilemma is something we should definitely work on). How about something like this.

proposal:

If were going to use BDD, we use it to encode the product design. Forgive the poor style and probably incomplete spec):

```gherkin
Scenario: Managers that don't manage the traits used by the integration when traversing a stage for read are bypassed and the input is passed through.
  Given the configured manager does not manage the `locatableContent` trait for read
  When a stage is composed
    Then the manager is invoked to determine its `managementPolicy` for a read context with a USD AR locale
    And a suitable debug message is logged
    And no other API calls are made.
    And the input data is passed to the `ArDefaultResolver`.

Scenario: Managers that manage the traits used by the integration when traversing a stage for read are used to resolve valid entity references and their resulting paths are passed through.
  Given the configured manager does manage the `locatableContent` trait for read
  When a stage is composed
     Then the manager is invoked to determine its `managementPolicy` for a read context with a USD AR locale
  When a resolvable input is encountered
  And the manager considers it a valid entity reference
     Then the manager is used to resolve the reference
     And the resulting path passed to the `ArDefaultResolver`.
  When a resolvable input is encountered
  And the manager does not consider it a valid entity reference
    Then no further API calls are made during the processing of that input
    And the input is passed to the `ArDefaultResolver`.
 ```

Rationale:
 - It coveres the product-level design requirements accurately
 - It defines how it should work over time when the tests fail
 - It doesn't dictate how the tests are achieved, as that is an implementation detail, rather than a behavioral requirement. 

Whether than then directly maps to some, or all the tests is an implementation choice to make?

(Hopefully this all reads ok and conveys the subtlety, its hard to do all this through typing)

**Comment by foundrytom** [comment] 2023-01-23 12:09
Closing in favor of https://github.com/OpenAssetIO/usdOpenAssetIOResolver/issues/8

**Closed as completed by foundrytom** 2023-01-23 12:09 UTC
